services:
  shopper_postgres:
    container_name: shopper-db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=shopper-db
    volumes:
      - postgres_data:/bitnami/postgresql

  app:
    container_name: shopper-app
    build:
      context: .
    ports:
      - "3333:3333"
    depends_on:
      - shopper_postgres
    environment:
      - PORT:3333
      - DATABASE_URL:postgresql://docker:docker@shopper_postgres:5432/shopper-db?schema=public
      - BASE_URL:http://localhost:3333
    volumes:
      - .:/usr/src

volumes:
  postgres_data:
