services:
  shopper_postgres:
    container_name: shopper-db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=shopper-db
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
